# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1044, 638)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.left_top_line = QtWidgets.QFrame(self.centralwidget)
        self.left_top_line.setGeometry(QtCore.QRect(20, 40, 181, 16))
        self.left_top_line.setStyleSheet(
            'font: 20pt "MS Shell Dlg 2";\n' 'font: 48pt "MS Shell Dlg 2";'
        )
        self.left_top_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.left_top_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.left_top_line.setObjectName("left_top_line")
        self.todobutton = QtWidgets.QPushButton(self.centralwidget)
        self.todobutton.setGeometry(QtCore.QRect(20, 0, 161, 41))
        self.todobutton.setStyleSheet('font: 20pt "MS Shell Dlg 2";')
        self.todobutton.setObjectName("todobutton")
        self.menu_line = QtWidgets.QFrame(self.centralwidget)
        self.menu_line.setGeometry(QtCore.QRect(210, 20, 20, 581))
        self.menu_line.setFrameShape(QtWidgets.QFrame.VLine)
        self.menu_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.menu_line.setObjectName("menu_line")
        self.left_under_line = QtWidgets.QFrame(self.centralwidget)
        self.left_under_line.setGeometry(QtCore.QRect(20, 350, 181, 16))
        self.left_under_line.setStyleSheet(
            'font: 20pt "MS Shell Dlg 2";\n' 'font: 48pt "MS Shell Dlg 2";'
        )
        self.left_under_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.left_under_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.left_under_line.setObjectName("left_under_line")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 50, 160, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.list1button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.list1button.setStyleSheet("")
        self.list1button.setObjectName("list1button")
        self.verticalLayout.addWidget(self.list1button)
        self.list2button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.list2button.setObjectName("list2button")
        self.verticalLayout.addWidget(self.list2button)
        self.list3button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.list3button.setObjectName("list3button")
        self.verticalLayout.addWidget(self.list3button)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 400, 160, 71))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.completebutton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.completebutton.setObjectName("completebutton")
        self.verticalLayout_2.addWidget(self.completebutton)
        self.deletebutton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.deletebutton.setObjectName("deletebutton")
        self.verticalLayout_2.addWidget(self.deletebutton)
        self.addlistbutton = QtWidgets.QPushButton(self.centralwidget)
        self.addlistbutton.setGeometry(QtCore.QRect(140, 540, 75, 23))
        self.addlistbutton.setObjectName("addlistbutton")
        self.top_line = QtWidgets.QFrame(self.centralwidget)
        self.top_line.setGeometry(QtCore.QRect(240, 50, 751, 16))
        self.top_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.top_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.top_line.setObjectName("top_line")
        self.highlight_label = QtWidgets.QLabel(self.centralwidget)
        self.highlight_label.setGeometry(QtCore.QRect(250, 10, 191, 41))
        self.highlight_label.setStyleSheet('font: 20pt "MS Shell Dlg 2";')
        self.highlight_label.setObjectName("highlight_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1044, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.list1button.setText(_translate("MainWindow", "list1"))
        self.list2button.setText(_translate("MainWindow", "list2"))
        self.list3button.setText(_translate("MainWindow", "list3"))
        self.completebutton.setText(_translate("MainWindow", "completed task"))
        self.deletebutton.setText(_translate("MainWindow", "deleted task"))
        self.addlistbutton.setText(_translate("MainWindow", "+ add list"))
        self.highlight_label.setText(_translate("MainWindow", "Highlight Task"))
        self.todobutton.setText(_translate("MainWindow", "TODO App"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
