# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stack.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.edit_button = QtWidgets.QPushButton(self.centralwidget)
        self.edit_button.setGeometry(QtCore.QRect(20, 280, 75, 23))
        self.edit_button.setObjectName("edit_button")
        self.setting_button = QtWidgets.QPushButton(self.centralwidget)
        self.setting_button.setGeometry(QtCore.QRect(20, 230, 75, 23))
        self.setting_button.setObjectName("setting_button")
        self.home_button = QtWidgets.QPushButton(self.centralwidget)
        self.home_button.setGeometry(QtCore.QRect(20, 180, 75, 23))
        self.home_button.setObjectName("home_button")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(140, 0, 491, 451))
        self.stackedWidget.setObjectName("stackedWidget")
        self.home_page = QtWidgets.QWidget()
        self.home_page.setObjectName("home_page")
        self.label = QtWidgets.QLabel(self.home_page)
        self.label.setGeometry(QtCore.QRect(210, 173, 111, 51))
        self.label.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.home_page)
        self.setting_page = QtWidgets.QWidget()
        self.setting_page.setObjectName("setting_page")
        self.label_2 = QtWidgets.QLabel(self.setting_page)
        self.label_2.setGeometry(QtCore.QRect(180, 170, 111, 51))
        self.label_2.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.setting_page)
        self.edit_page = QtWidgets.QWidget()
        self.edit_page.setObjectName("edit_page")
        self.label_3 = QtWidgets.QLabel(self.edit_page)
        self.label_3.setGeometry(QtCore.QRect(190, 210, 111, 51))
        self.label_3.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.edit_page)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.home_button.clicked.connect(lambda:self.stackedWidget.setCurrentWidget(self.home_page))
        self.setting_button.clicked.connect(lambda:self.stackedWidget.setCurrentWidget(self.setting_page))
        self.edit_button.clicked.connect(lambda:self.stackedWidget.setCurrentWidget(self.edit_page))
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.edit_button.setText(_translate("MainWindow", "edit"))
        self.setting_button.setText(_translate("MainWindow", "setting"))
        self.home_button.setText(_translate("MainWindow", "home"))
        self.label.setText(_translate("MainWindow", "home"))
        self.label_2.setText(_translate("MainWindow", "setting"))
        self.label_3.setText(_translate("MainWindow", "edit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
